id: IDB3B1B1B
legacy_id: P005553
ocr_import_info:
  bdrc_scan_id: W1KG22150
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T19:21:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T07:06:44.464988+00:00'
last_modified: 2022-08-27 15:09:46.943331
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22150
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22150
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆུ་འབྲེལ་བོད་ཀྱི་ཡིག་རྙིང་ཕྱོགས་བསྒྲིགས།
statistics:
  ocr_word_mean_confidence_index: 0.7270395448810104
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I1KG22160:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22160
      total_pages: 422
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG22160.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7335671367348813
    legacy_id: v002
  I1KG22159:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22159
      total_pages: 408
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22159.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7148309427903526
    legacy_id: v001
  I1KG22162:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22162
      total_pages: 472
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG22162.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7605627555711106
    legacy_id: v004
  I1KG22161:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22161
      total_pages: 430
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG22161.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7093584387152584
    legacy_id: v003
  I1KG22163:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22163
      total_pages: 458
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG22163.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7150352640182188
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
